---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 22/07/2022 17:05
---

local snd <const> = playdate.sound

local masterplayer <const> = masterplayer

masterplayer.sawToothInstrument = { id=snd.kWaveSawtooth, name="Sawtooth" }

masterplayer.instruments = {
    { id=snd.kWaveSine, name="Sine" },
    { id=snd.kWaveSquare, name="Square" },
    masterplayer.sawToothInstrument,
    { id=snd.kWaveTriangle, name="Triangle" },
    { id=snd.kWaveNoise, name="Noise" },
    { id=snd.kWavePOPhase, name="POPhase" },
    { id=snd.kWavePODigital, name="PODigital" },
    { id=snd.kWavePOVosim, name="POVosim" },
}

masterplayer.instrumentProps = {}

function masterplayer.addInstrument(instrumentProps, name)
    print("adding instrument", instrumentProps, name)
    masterplayer.instruments[#masterplayer.instruments+1] = { name=name, id=instrumentProps.id }
    masterplayer.instrumentProps[instrumentProps.id] = instrumentProps
end
