---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 25/08/2022 22:19
---

import "CoreLibs/object"
import "midi.lua"

class("MasterPlayer").extends()

function MasterPlayer:init(songPath)
    MasterPlayer.super.init()

    if self.sequence then
        self.sequence:stop()
        self.trackProps = nil
    end
    self.trackProps = json.decodeFile(songPath .. ".json")
    print(songPath, trackProps)
    self.sequence, self.trackProps = loadMidi(songPath, self.trackProps)
end

function MasterPlayer:play()
    self.sequence:play()
end

function MasterPlayer:stop()
    self.sequence:stop()
end

--function MasterPlayer.new(songPath)
--    _, self.trackProps = loadMidi(songPath, self.trackProps)
--    return MasterPlayer(songPath)
--end
