---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 25/08/2022 22:19
---

local masterplayer <const> = masterplayer

class("MasterPlayer", {}, masterplayer).extends()

function masterplayer.MasterPlayer:init(songPath)
    MasterPlayer.super.init(self)

    if self.sequence then
        self.sequence:stop()
        self.trackProps = nil
    end
    self.trackProps = json.decodeFile(songPath .. ".json")
    print(songPath, trackProps)
    self.sequence, self.trackProps = masterplayer.loadMidi(songPath, self.trackProps)
end

function masterplayer.MasterPlayer:play()
    self.sequence:setLoops(0, self.sequence:getLength())
    self.sequence:play()
end

function masterplayer.MasterPlayer:stop()
    self.sequence:stop()
end

function masterplayer.MasterPlayer:setVolume(vol)
    for i, item in ipairs(self.trackProps) do
        local effectiveVolume = vol * item.volume
        self.sequence:getTrackAtIndex(i):getInstrument():setVolume(effectiveVolume)
    end
end

function masterplayer.new(songPath)
    return masterplayer.MasterPlayer(songPath)
end
