---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 25/08/2022 22:19
---

local masterplayer <const> = masterplayer

class("MasterPlayer", {}, masterplayer).extends()

function masterplayer.MasterPlayer:init(songPath)
    MasterPlayer.super.init(self)

    if self.sequence then
        self.sequence:stop()
        self.trackProps = nil
    end
    self.trackProps = json.decodeFile(songPath .. ".json")
    print(songPath, trackProps)
    self.sequence, self.trackProps = masterplayer.loadMidi(songPath, self.trackProps)
    if not self.sequence then
        self.error = self.trackProps
    else
        for i,item in ipairs(trackProps) do
            local inst, addedSynths = masterplayer.createInstrument(item)
            self.synthReferences = lume.concat(self.synthReferences, addedSynths)
            sequence:getTrackAtIndex(i):setInstrument(inst)
        end
    end
end

function masterplayer.MasterPlayer:play()
    self.sequence:setLoops(0, self.sequence:getLength())
    self.sequence:play()
end

function masterplayer.MasterPlayer:stop()
    self.sequence:stop()
end

function masterplayer.MasterPlayer:setVolume(vol)
    for i, item in ipairs(self.trackProps) do
        local effectiveVolume = vol * item.volume
        self.sequence:getTrackAtIndex(i):getInstrument():setVolume(effectiveVolume)
    end
end

function masterplayer.new(songPath)
    local player = masterplayer.MasterPlayer(songPath)
    if not player.error then
        return nil, player.error
    else
        return player
    end
end
