---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 22/07/2022 14:45
---

import "./SampleCache.lua"

local masterplayer <const> = masterplayer
local lume <const> = masterplayer.lume
local snd <const> = playdate.sound
local defaultSampledVolume <const> = 0.5
local defaultWaveVolume <const> = 0.2
local defaultWaveAttack <const> = 0
local defaultWaveDecay <const> = 0.15
local defaultWaveSustain<const> = 0.2
local defaultWaveRelease <const> = 0

function masterplayer.newWaveSynth(trackProps)
    local s = snd.synth.new(trackProps.instrument.id or snd.kWaveSawtooth)
    s:setVolume(trackProps.volume or defaultWaveVolume)
    s:setADSR(
        trackProps.attack or defaultWaveAttack,
        trackProps.decay or defaultWaveDecay,
        trackProps.sustain or defaultWaveSustain,
        trackProps.release or defaultWaveRelease
    )
    return s
end

function masterplayer.createSampleSynth(samplePath, trackProps)
    local sample = masterplayer.sampleCache:getOrLoad(samplePath)
    if not sample then
        error("sample not found: " .. samplePath)
    end
    local s = snd.synth.new(sample)
    s:setVolume(trackProps.volume or defaultSampledVolume)
    -- no drum defaults yet, use wave defaults
    s:setADSR(
        trackProps.attack or defaultWaveAttack,
        trackProps.decay or defaultWaveDecay,
        trackProps.sustain or defaultWaveSustain,
        trackProps.release or defaultWaveRelease
    )
    return s
end

function masterplayer.createWaveInstrument(trackProps)
    local inst = snd.instrument.new()
    local addedSynths = {}
    for _=1, trackProps.polyphony do
        local synth = masterplayer.newWaveSynth(trackProps)
        table.insert(addedSynths, synth)
        inst:addVoice(synth)
    end
    return inst, addedSynths
end

function masterplayer.createSampledInstrument(trackProps)
    local inst = snd.instrument.new()
    local instrumentId = trackProps.instrument.id
    local instrumentProps = masterplayer.instrumentProps[instrumentId]
    if not instrumentProps then
        error("Could not find sample instrument " .. instrumentId .. ". Did you install the Toybox and call masterplayer.addInstrument()?")
    end
    print("creating sampled instrument for ", instrumentProps.id)
    local synth, noteProps, transpose, noteStart, noteEnd, noteRoot, offset
    local addedSynths = {}
    local addedNoteProps = {}
    for _, note in ipairs(trackProps.notes) do
        noteProps = instrumentProps[note]
        if noteProps then
            if not lume.find(addedNoteProps, noteProps) then
                noteStart = noteProps.noteStart or note
                noteEnd = noteProps.noteEnd or noteStart
                noteRoot = noteProps.noteRoot or noteStart
                offset = noteRoot - noteStart
                transpose = 60 - noteStart - offset-- the default noteRoot is C4 (midi note 60)
                synth = masterplayer.createSampleSynth( noteProps.path, trackProps)
                table.insert(addedSynths, synth)
                inst:addVoice(synth, noteStart, noteEnd, transpose )
                table.insert(addedNoteProps, noteProps)
            end
        else
            print("instrument does not support note " .. note)
        end
    end
    return inst, addedSynths
end

function masterplayer.createInstrument(trackProps)
    if type(trackProps.instrument.id) == "string" then
        local inst, addedSynths = masterplayer.createSampledInstrument(trackProps)
        return inst, addedSynths
    else
        local inst, addedSynths = masterplayer.createWaveInstrument(trackProps)
        return inst, addedSynths
    end
end

local function getNotesForTrack(track)
    local notes = {}
    for _, item in ipairs(track:getNotes(1, track:getLength())) do
        notes[item.note] = true
    end
    return lume.sort(lume.keys(notes))
end

local function createTrackProps(s)
    local numTracks = s:getTrackCount()
    local trackProps = {}
    local active = {}
    local poly = 0

    for i=1,numTracks do
        local track = s:getTrackAtIndex(i)
        if track ~= nil then
            local polyphony = track:getPolyphony()
            if polyphony > 0 then active[#active+1] = i end
            if polyphony > poly then poly = polyphony end
            print("track "..i.." has polyphony ".. polyphony)

            local notes = getNotesForTrack(track)
            local props = {
                polyphony = polyphony,
                isMuted = #notes < 1,
                isSolo = false,
                notes = notes
            }
            trackProps[i] = props

            print("Creating Sawtooth for track", i)
            props.instrument = masterplayer.sawToothInstrument
            props.volume = defaultWaveVolume
            props.attack = defaultWaveAttack
            props.decay = defaultWaveDecay
            props.sustain = defaultWaveSustain
            props.release = defaultWaveRelease
        end
    end

    return trackProps
end

function masterplayer.loadTrackProps(s, trackProps)
    local numTracks = s:getTrackCount()
    for i=1,numTracks do
        local track = s:getTrackAtIndex(i)
        if not trackProps[i].notes then
            trackProps[i].notes = getNotesForTrack(track)
        end
    end
    return trackProps
end

function masterplayer.loadMidi(path, _trackProps)
    local trackProps = _trackProps or {}
    local s = snd.sequence.new(path)
    local ntracks = s:getTrackCount()
    print("ntracks", ntracks)
    if ntracks == 0 then
        if playdate.file.exists(path) then
            return nil, "Could not load " .. path .. ". File contains 0 tracks"
        end
        return nil, "Could not load " .. path .. ". File does not exist"
    end

    if ntracks == #trackProps then
        return s, masterplayer.loadTrackProps(s, trackProps)
    else
        print("Creating track props for", path)
        return s, createTrackProps(s)
    end
end
