---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ninovanhooff.
--- DateTime: 29/09/2022 22:21
---

import "CoreLibs/object"

local loadSample = playdate.sound.sample.new

class("SampleCache").extends()

function SampleCache:init()
    SampleCache.super.init()
    self.map = {}
end

function SampleCache:getOrLoad(path)
    if self.map[path] then
        printf("SampleCache hit", path)
        return self.map[path]
    end

    printf("SampleCache miss", path)
    local sample = loadSample(path)
    self.map[path] = sample
    return sample
end

-- global singleton
if not sampleCache then
    sampleCache = SampleCache()
end
